### ISSUE TITLE
Ubuntu builds don't contain hdhomerun support

### ISSUE THREAD

**Issue by gdevenyi** [tvheadend/tvheadend-build#2]
Using a fresh trusty install, hdhomerun can be pinged and discovered.

Both stable and unstable builds don't find any hdhomerun tuners.

**Comment by adamsutton** [comment]
Another dep not included in the control file. I'll take a look. Gonna have to so something more general about this in future I think.

**Comment by dreamcat4** [comment]
Hi @adamsutton,
Thanks for now supplying new repos on bintray. This will be expecially appreciated for those new i386 and ARM support added.

Anyway just to bring attention any other possible user-requested build flag(s). For example, this one (which only matters if static ffmpeg),

http://tvheadend.org/issues/3438

make me wonder if there is also an equiv. AMD flag too. And whether we should / should not be supporting.


Perhaps other ones too. It can be checked up on here:

https://github.com/tvheadend/tvheadend-build/blob/master/ubuntu/deps/Dockerfile#L8

https://github.com/tvheadend/tvheadend-build/blob/master/ubuntu/master/Dockerfile#L15

Many thanks.

**Comment by adamsutton** [comment]
@dreamcat4 hey been keeping my eye open for you on #hts. My plan is to look more closely at how we manage builds going forward, need to balance having the right components in the official builds with not overburdening self-builders (ffmpeg isn't exactly quick) and also not having massive diff between the two. Clearly not a simple answer.

I think for now I've mostly got the major missing elements. I'm not using bundle, that really only ever intended for embedded platforms, not that it's a major issue to include it.

I'm also looking at probably replacing the current build system to simplify things. The current one is actually still very much tied to the old apt repo, and I just push the finished binaries to bintray.

Ping me next time your in #hts, I'm not around loads, but would be nice to chat things through with you.

**Comment by dreamcat4** [comment]
I agree that the default build settings in src/git should not include all this static stuff. When users checkout the sources and want to self build with their own set of preferred flags.

Yet static ffmpeg totally worth it. I can say from managing last 6 months those builds before you came back, there were 0 reports about packaging problems or issues with using / installing the .deb files themselves. Not a peep or word from anyone.

Just generally speaking - to make the officially distributed packages as 'standalone' packages. I.e. everything as static help users a lot. Because of many complex reasons, but here are some important ones which often get ignored:

* To reduce false-positive user reports, which un-burdens both users and core developers who have to wade through such reports.
* To simplify installation instructions, which are the same for all to follow.
* Better user experience, for example if they end up needing to use such optional feature(s) later on. But didn't think to install them initially / can't remember what they did.
* To make the heavier build 1 time is less efficient. However doing it in a central location means the same standalone binary is getting to many users. (no need for multiple variants). So that is efficient bang-for-buck.

In terms of libav / ffmpeg specifically: well I don't use the tvheadend transcoding feature either myself Adam! Yet if I didn't include it there would be so many people saying / asking "why doesnt transcoding work?"... and "transcoding is broken". etc. Then it just would not be worth my time to have to keep explaining to them over and over again how to install it, and them to say "well i'm on distro XYZ, and we have a different ffmpeg / libav version, how do i do it?"... don't have answers to such questions.

Then this issue, hdhomerun ^^. Well it seems to be the most popular hardware device used in north america for getting the ATSC input. So that's another bifrucation / segmentation within the user base. Again avoided merely with static compilation.

Now I know that doesn't solve your issues with it taking a f***ton of time to compile libav for armhf. But I can link you to cjwatson's work on launchpad.net. "Sometime 2016 hopefully" he says. Then you could later consider moving it all off to launchpad.net instead of bogging down on your own systems. Just subscribe to the 6 bugs in my watch list and you will be updated:

https://bugs.launchpad.net/~dreamcat4/+bugs?orderby=-date_last_updated&start=0

**Comment by adamsutton** [comment]
@dreamcat4 maybe I'm misreading your response, but the number of !'s comes across a tad defensive / aggressive? I applogise if I got the tone wrong.

But let me put your concerns at rest. I'm not against including ffmpeg (static) or hdhomerun in the official builds, I wouldn't have done so if not. And I share your concerns about random questions about this or that not working etc... And I'm definitely in the ffmpeg static camp rather than relying on distro supplied, the later is just fraught with problems.

My comments about looking at what gets included is just a more general one, i.e. whether there is a better/simpler way to describe these things to ensure best possible cohesion between self build and official packages. Not that I'm planning to throw things out of official packages, that would never be my aim. It might be that we look at an addon approach (and that might be relevant to some, not all, aspects discussed here), which has some other benefits. But that's just random musing's at the moment.

And I'm not worried about taking up system time. We have a dedicated box that does all the TVH hosting and building. And since we've not exactly got the most actively visited site. Taking up most of the CPU for an hour or so while building all packages is neither here nor there. And if we really needed more resource, it wouldn't be difficult to acquire it.

Anyway, closing this issue since the latest builds include ffmpeg and hdhomerun, and there omission from the official packages was never intentional.
